image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      source ~/emsdk/emsdk_env.sh
      scons platform=web target=editor
  - command: python3 platform/web/serve.py --no-browser
ports:
  - name: Web Editor
    port: 8060
    onOpen: open-browser
